# Generated by Django 5.2.6 on 2025-10-01 15:34

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('coordinates', models.JSONField(default=dict, validators=[app.models.validate_coordinates])),
                ('location_type', models.CharField(choices=[('seated', 'Seated'), ('general_admission', 'General Admission')], max_length=100)),
                ('date_time', models.DateTimeField()),
                ('tickets_available', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, validators=[app.models.validate_user_is_organiser])),
            ],
        ),
    ]
